--DROP TABLE USUARIOS, ROLES, VENTAS, PRODUCTOS, PROVEEDORES, COMPRAS, ALMACEN, CLIENTES

--INSERT INTO PRODUCTOS VALUES('CASA', 125000, 21, 0)


SELECT * FROM USUARIOS
SELECT * FROM PROVEEDORES
SELECT * FROM PRODUCTOS
--SELECT * FROM COMPRAS

INSERT INTO COMPRAS VALUES ('prueba')